CHARGER ES DONNEES

In [59]:
import pandas as pd
films = pd.read_csv('./donnees/export_films.csv', sep='\t', low_memory=False)
films_personnes = pd.read_csv('./donnees/export_films_personnes.csv',sep='\t', low_memory=False)

on explode les colonnes en utilisant la fonction eval

In [60]:
films = films[(films['genres_x'].str.contains('Movie')==False)]
films

,Unnamed: 0.1,Unnamed: 0,adult,budget,genres_x,id_tmdb,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,title,vote_average,vote_count,directors,writers,year
0,0,70,False,12800000,"['Drama', 'Crime']",16,tt0168629,en,Dancer in the Dark,"Selma, a Czech immigrant on the verge of blind...",...,40031879,141,['en'],Released,Dancer in the Dark,7.881,1555,nm0001885,"nm0001885,nm0797604",2000
1,1,109,False,140000000,"['Adventure', 'Fantasy', 'Action']",22,tt0325980,en,Pirates of the Caribbean: The Curse of the Bla...,"Jack Sparrow, a freewheeling 18th-century pira...",...,655011224,143,['en'],Released,Pirates of the Caribbean: The Curse of the Bla...,7.800,18710,nm0893659,"nm0254645,nm0744429,nm0064181,nm0938684",2003
2,2,133,False,30000000,"['Action', 'Crime']",24,tt0266697,en,Kill Bill: Vol. 1,"An assassin is shot by her ruthless employer, ...",...,180906076,111,"['en', 'ja', 'fr']",Released,Kill Bill: Vol. 1,7.970,15748,nm0000233,"nm0000233,nm0000235",2003
3,3,154,False,200000000,"['Adventure', 'Fantasy', 'Action']",58,tt0383574,en,Pirates of the Caribbean: Dead Man's Chest,Captain Jack Sparrow works his way out of a bl...,...,1065659812,151,"['en', 'tr', 'el', 'zh']",Released,Pirates of the Caribbean: Dead Man's Chest,7.340,14465,nm0893659,"nm0254645,nm0744429,nm0064181,nm0938684",2006
4,4,196,False,2000000,"['Thriller', 'Crime', 'Drama']",67,tt0445620,en,Paradise Now,Two childhood friends are recruited for a suic...,...,3395627,90,"['ar', 'en']",Released,Paradise Now,6.941,219,nm0009463,"nm0009463,nm1178208,nm0388293",2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11011,12765,767462,False,0,['Drama'],215034,tt3118628,en,Bastardo,Larger-than-life characters populate director ...,...,0,106,['ar'],Released,Bastard,7.000,1,nm0067946,"nm0067946,nm2144991",2013
11012,12767,768121,False,0,['Drama'],219173,tt1576452,es,Por tu culpa,"Are we what others see, or are we what we allo...",...,0,87,['es'],Released,It's Your Fault,6.000,5,nm1318393,"nm1318393,nm1196938",2010
11013,12768,768702,False,0,['Action'],222409,tt1512732,en,Braille,Nick's blindness is symbolic to his regret for...,...,0,90,[],Released,Braille,6.000,1,nm2065393,"nm2065393,nm1863128",2011
11014,12769,769648,False,0,['Documentary'],228655,tt2007418,fr,Les trois disparitions de Soad Hosni,This haunting and beautifully formed documenta...,...,0,70,"['ar', 'en', 'fr']",Released,The Three Disappearances of Soad Hosni,6.000,1,nm1645751,nm1645751,2011
11015,12770,769907,False,0,"['Thriller', 'Horror', 'Action', 'Adventure', ...",231003,tt2011045,en,Hombre Y Tierra,"Mauro Bosque was an adventurer, a survivalist,...",...,0,82,['es'],Released,Hombre Y Tierra,5.200,3,nm1870338,"nm1870338,nm2566773",2011

In [61]:
films['genre'] = films['genres_x'].apply(eval)

In [62]:
films_prepa = films.explode('genre')

In [63]:
films_prepa_cat = films_prepa[['genre']]
films_cat_dummies = pd.get_dummies(films_prepa_cat)

In [64]:
films_cat_dummies

,genre_Action,genre_Adventure,genre_Animation,genre_Comedy,genre_Crime,genre_Documentary,genre_Drama,genre_Family,genre_Fantasy,genre_History,genre_Horror,genre_Music,genre_Mystery,genre_Romance,genre_Science Fiction,genre_Thriller,genre_War,genre_Western
0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
0,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11015,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
11015,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
11015,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11015,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11015,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False

In [66]:
films_prepa['original_language'].value_counts()

original_language
en    9385
fr    4994
ja    2305
hi     972
ko     971
      ...
gu       1
xh       1
mg       1
kl       1
sw       1
Name: count, Length: 90, dtype: int64

In [38]:
films_prepa.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'adult', 'budget', 'genres_x', 'id_tmdb',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'title',
       'vote_average', 'vote_count', 'directors', 'writers', 'year', 'genre',
       'pays', 'langue_parlee'],
      dtype='object')

2. SAVOIR CE QU ON VEUT PREDIRE

In [ ]:
#colonnes à sup: adults, budget id_tmdb, imbd, original title, overview,poster_path,, 'release_date',
#'revenue', 'vote_count''directors', 'writers','spoken_languages',,production_countries

In [ ]:
#colonne à garder : genre',original_language','popularity','runtime', ,'vote_average', 'year'

3. DECLARATION

In [ ]:
X = films[['genres_x','original_language','popularity','production_countries','runtime', 'spoken_languages','title','vote_average', 'year',]]